services:
  mqserver:
    image: ghcr.io/xyz/xyz:main
    container_name: mqserver
    restart: unless-stopped
    environment:
      - BASE_DIRECTORY=/data
      - LOCAL_ASSETS_DIRECTORY=/App
      - CACHE_INFO_LOCATION=/caches/RemovedDuplicates/__info
      - SETTINGS_FILE_LOCATION=/settings/settings.txt
      - DEFAULT_USERNAME=
      - DEFAULT_PASSWORD=
      - DEFAULT_EMAIL=
      - DEFAULT_GENDER=
      - DEFAULT_DOB=
    ports:
      - 9339:9339
      - 80:80
    volumes:
      - /docker/mqserver/data:/data
      - /docker/mqserver/caches:/caches
      - /docker/mqserver/settings:/settings
    networks:
      - proxy
networks:
  proxy:
    external: true
