services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
      - /root/.docker:/root/.docker:ro
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - proxy
networks:
  proxy:
    external: true
